name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux64
          - os: macos-latest
            platform: macosarm64
          - os: windows-latest
            platform: windows64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache CEF
        id: cache-cef
        uses: actions/cache@v4
        with:
          path: cef/${{ matrix.platform }}
          key: cef-${{ matrix.platform }}-v1

      - name: Install dependencies
        run: bun ci # Will download cef as well

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxext-dev libxrandr-dev libxss-dev xvfb libgtk-3-0 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2t64

      - name: Build CEF
        run: bun run build:cef

      - name: TypeScript Check
        run: bun run typecheck

      - name: Run Tests (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run --auto-servernum bun run test
        env:
          LD_LIBRARY_PATH: build

      - name: Run Tests (macOS)
        if: matrix.os == 'macos-latest'
        run: bun run test
        env:
          LD_LIBRARY_PATH: build

      - name: Run Tests (Windows)
        if: matrix.os == 'windows-latest'
        run: bun run test
        env:
          LD_LIBRARY_PATH: build
          Path: "build;${{ env.Path }}"
